preferred_syntax = :sass
http_path = '/'
css_dir = 'pipeline/public/stylesheets'
sass_dir = 'pipeline/public/sass'
images_dir = 'assets/images'
javascripts_dir = 'pipeline/public/javascripts'
relative_assets = true
line_comments = true
# output_style = :compressed
